=== SriShruti24/FSD-IT-A-Shruti-Srivastava-/students.dtd
<!ELEMENT students (student+)>

<!ELEMENT student (name, dob, email, address?, course+, marks)>
<!ATTLIST student
  rollno ID #REQUIRED
  gender (Male|Female|Other) #REQUIRED
>

<!ELEMENT name (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ELEMENT course (#PCDATA)>
<!ATTLIST course code (CS101|MA101|PH101|EE101) #REQUIRED>

<!ELEMENT marks (total, grade)>
<!ELEMENT total (#PCDATA)>
<!ELEMENT grade (#PCDATA)>

=== SriShruti24/FSD-IT-A-Shruti-Srivastava-/students.xml
<!DOCTYPE students SYSTEM "students.dtd">
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "students.dtd">
<students>
  <student rollno="S001" gender="Female">
    <name>Shruti Srivastava</name>
    <dob>2003-09-12</dob>
    <email>shruti@example.com</email>
    <address>Lucknow, India</address>

    <course code="CS101">Introduction to CS</course>
    <course code="MA101">Calculus I</course>

    <marks>
      <total>186</total>
      <grade>A</grade>
    </marks>
  </student>

  <student rollno="S002" gender="Male">
    <name>Arjun Verma</name>
    <dob>2002-02-05</dob>
    <email>arjun.verma@example.org</email>

    <course code="PH101">Physics I</course>
    <course code="EE101">Basic Electrical</course>

    <marks>
      <total>172</total>
      <grade>B+</grade>
    </marks>
  </student>
</students>
